"""empty message

Revision ID: 3e7b76f0bbf0
Revises: 8b192141bc0c
Create Date: 2020-09-23 01:40:23.591033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7b76f0bbf0'
down_revision = '8b192141bc0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docAuth', sa.Integer(), server_default='1', nullable=False))

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docAuth', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('docAuth')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('docAuth')

    # ### end Alembic commands ###
