"""empty message

Revision ID: 8b192141bc0c
Revises: 31e6bc9c6f1c
Create Date: 2020-09-22 22:23:38.936470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b192141bc0c'
down_revision = '31e6bc9c6f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_doctor_doctorName'), ['doctorName'])
        batch_op.create_unique_constraint(batch_op.f('uq_doctor_doctorNumber'), ['doctorNumber'])

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_patient_patientName'), ['patientName'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_patient_patientName'), type_='unique')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_doctor_doctorNumber'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_doctor_doctorName'), type_='unique')

    # ### end Alembic commands ###
