"""empty message

Revision ID: bfbcee1ddde1
Revises: 3e7b76f0bbf0
Create Date: 2020-10-18 22:38:08.742130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfbcee1ddde1'
down_revision = '3e7b76f0bbf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patientHash', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('patientHash')

    # ### end Alembic commands ###
